# name: 'Create PR from new feature/bugfix/'
# on:
#   push:

# jobs:
#   test:
#     if: github.event_name  == 'push'
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Configuration without Checkout"
#         id: without_checkout
#         uses: mikepenz/release-changelog-builder-action@v2
#         with:
#           toTag: "v0.0.3"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
#       - name: Echo Configuration without Checkout Changelog
#         env:
#           CHANGELOG: ${{ steps.without_checkout.outputs.changelog }}
#         run: echo "CHANGELOG"

#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#         # Showcase the most minimal configuration possible
#       - name: "Minimal Configuration"
#         id: minimal_release
#         uses: mikepenz/release-changelog-builder-action@v2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
#       - name: Echo Minimal Configuration Changelog
#         env:
#           CHANGELOG: ${{ steps.minimal_release.outputs.changelog }}
#         run: echo "$CHANGELOG"

#         # Showcases a more complex configuration, providing a configuration, and specifically referencing owner, repo, from and to tag
#       - name: "Complex Configuration"
#         id: complex_release
#         uses: mikepenz/release-changelog-builder-action@v2
#         with:
#           configuration: ".github/workflows/changelog_configuration/configuration_complex.json"
#           owner: "mikepenz"
#           repo: "release-changelog-builder-action"
#           fromTag: "v0.0.1"
#           toTag: "v0.0.3"
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Echo Complex Configuration Changelog
#         env:
#           CHANGELOG: ${{ steps.complex_release.outputs.changelog }}
#         run: echo "CHANGELOG"

#         # Showcases the capability to generate the changelog for an external repository provided
#       - name: "External Repo Configuration"
#         id: external_changelog
#         uses: mikepenz/release-changelog-builder-action@v2
#         with:
#           configuration: ".github/workflows/changelog_configuration/configuration_complex.json"
#           owner: "mikepenz"
#           repo: "MaterialDrawer"
#           fromTag: "v8.1.0"
#           toTag: "v8.1.6"
#           token: ${{ secrets.PERSONAL_TOKEN }}

#       - name: Echo External Repo Configuration Changelog
#         env:
#           CHANGELOG: ${{ steps.external_changelog.outputs.changelog }}
#         run: echo "$CHANGELOG"
