- name: Create Pull Request
  id: cpr
  on:
  push:
    branches:
      - feature/**
      - bugfix/**
  uses: peter-evans/create-pull-request@v3
- name: Check outputs
  run: |
    echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
