name: Create a Draft PR to develop from feature or bugfix

on:
  push:
    branches:
      - 'bugfix/**'
      - 'feaure/**'
jobs:
  createADraftPRToDevelopFromFeatureOrBugfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Update Author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
    
      - name: Raise Draft PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: develop
          title: "demo for auto pr"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
