name: 'Open PR to main branch when a new release/hotfix branch is pushed'

on:
  push:
    branches:
      - hotfix/**
      - release/**

jobs:
  createAPRToMainFromReleaseOrHotfix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update AUTHORS
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      
      - name: Raise Draft PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          base: main
          title: "${{ steps.extract_branch.outputs.branch }}"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation complete de description.
          token: ${{ secrets.GITHUB_TOKEN }}

