name: 'Create a Draft PR to develop from feature or bugfix'
on:
  push:
    branches:
      - bugfix/**
      - feature/**
jobs:
  createADraftPRToDevelopFromFeatureOrBugfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Update Author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
    
      - name: Raise Draft PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}
          base: develop
          title: "${{ steps.extract_branch.outputs.branch }}"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation complete de description.
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
