name: Open Draft PR to develop when a new feature/bugfix branch is pushed.
on:
  push:
    branches:
      - feature/**
      - bugfix/**
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the Author name
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          # commit-message: update authors
          title: Update $AUTHORS AUTHORS
          # body: Credit new contributors by updating AUTHORS
          # branch: update-authors
          reviewers: GustavoDuregger, 4rthurmonteiro, lstonussi, atrope, koga187, nferreira
          draft: true
          labels: feature, fix, test
