name: Update AUTHORS
on:
  create:
    branches:
      - feature/**
      - bugfix/**
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    # Check if the event is not triggered by a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Open Draft PR to develop when a new feature/bugfix branch is pushed.
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: develop
          # commit-message: update authors
          title: Update $AUTHORS
          # body: Credit new contributors by updating AUTHORS
          # branch: update-authors
          # reviewers: [GustavoDuregger, 4rthurmonteiro, lstonussi, atrope, koga187, nferreira, devs-oneapp]
          draft: true
          labels: feature, fix, test
